import { chatCompletion, chatCompletionStream, defaultModels } from "@/services/llm/llm";
import {
  chatWithTruncationRetry,
  languageInstruction,
  truncateCode,
  type GenerateOptions,
} from "@/services/generation/shared";
import { getSdkPromptLines } from "@/services/connections/registry";

type TriggerKind = "schedule" | "manual" | "webhook";

const TRIGGER_DEFAULT_SCHEDULE = "0 8 * * *";

/** Default schedule for the trigger ("" for an unscheduled script). */
function scheduleFallback(triggerKind: TriggerKind): string {
  return triggerKind === "schedule" ? TRIGGER_DEFAULT_SCHEDULE : "";
}

function buildScriptSystem(triggerKind: TriggerKind): string {
  const sdkLines = getSdkPromptLines("home").join("\n    ");
  const scheduling =
    triggerKind === "schedule"
      ? `- The job is \`async function main(home)\`, run server-side according to a 5-field cron expression.\n- You MUST provide the \`schedule\` field in the output JSON (5-field cron expression: minute hour day-of-month month day-of-week, e.g. 0 8 * * 1 = every Monday at 8am).`
      : triggerKind === "manual"
        ? `- The job is \`async function main(home)\`, run server-side on demand (manual trigger, e.g. a button in an app). No schedule: the output JSON does NOT contain a \`schedule\` field.`
        : `- The job is \`async function main(home)\`, run server-side when an inbound webhook arrives (public POST). The webhook's JSON body is available through \`home.webhook.payload\` (null when absent). No schedule: the output JSON does NOT contain a \`schedule\` field.`;
  const jsonContract =
    triggerKind === "schedule"
      ? `{
  "schedule": "5-field cron expression (e.g. 0 8 * * 1)",
  "name": "short job name",
  "code": "the complete JS code of async function main(home) { ... }"
}`
      : `{
  "name": "short job name",
  "code": "the complete JS code of async function main(home) { ... }"
}`;
  return `You are a developer writing a job (server script) for a small household app.

CONTRACT:
${scheduling}
- The job is a JavaScript \`async function main(home)\` executed server-side.
- \`home\` is the SDK provided by the platform. Use ONLY these methods, with EXACTLY these signatures (never invent a method or a parameter):
    - \`home.storage.get(key)\`, \`home.storage.set(key, value)\`, \`home.storage.list()\`, \`home.storage.remove(key)\` (the script's own JSON KV)
    - \`home.app(appId).storage.*\` — same API (get/set/list/remove/table) but against an existing app's storage. Use it whenever the job must feed or read an app; the appId must be supplied by the user, never invent one.
    - \`home.storage.global.get(key)\`, \`.set(key, value)\`, \`.list()\`, \`.remove(key)\` (KV shared across the household)
    - \`home.storage.table.add(key, row)\` → created row (auto-generated id), \`home.storage.table.update(key, id, patch)\` → updated row, \`home.storage.table.remove(key, id)\` → {ok, removed}, \`home.storage.table.toggle(key, id, field?)\` → row — atomic CRUD on an array of objects stored under \`key\`, without rewriting the whole list (prefer it over a whole get/set for collections)
${sdkLines}
     - \`home.http.fetch(url, {method?, headers?, body?})\` → {status, body, headers} (public fetch, private IPs blocked)
     - \`home.browser.open(url, {timeoutMs?})\` → {sessionId, url, title, text} (public web page, Lightpanda)
     - \`home.browser.click(sessionId, selector)\`, \`home.browser.fill(sessionId, selector, value)\`, \`home.browser.wait(sessionId, selector, timeoutMs?)\`
     - \`home.browser.text(sessionId, selector?)\`, \`home.browser.html(sessionId, selector?)\`, \`home.browser.evaluate(sessionId, expression)\`, \`home.browser.close(sessionId)\`
     - \`home.ai.chat(prompt, {system?, temperature?, maxTokens?})\` → string (text generated by the owner's LLM); \`home.ai.messages([{role: "system"|"user"|"assistant", content}, ...], opts?)\` → string (multi-turn)
     - \`home.ai.chatStream(prompt, opts, onToken)\` / \`home.ai.messagesStream(messages, opts, onToken)\` → string (same as above but streamed: \`onToken\` is called per token, useful for live output)
    All external data goes through \`home\`. Handle errors with try/catch and use console.log to trace.
- IMPORTANT: AI calls (\`home.ai.*\`) take several seconds — use them sparingly (a run is capped at 60 s).
- OPTIONAL: you may structure the code into phases for the execution flow — two syntaxes, 2-5 groups max. If you use neither, the engine still traces every call automatically:
  1. Wrapper \`await home.step("Label", async () => { ... })\` — the \`home.*\` calls made inside become its children.
  2. Comment pragma \`// @step Label\` — implicit scope until the next \`// @step\` or the end of \`main\` (the most concise):
    \`\`\`js
    // @step Read unread mail
    const mails = await home.google.gmail.search("is:unread", 10);
    // @step Summarise and send
    const summary = await home.ai.chat("Summarise: " + JSON.stringify(mails));
    await home.mail.send({ to: "me@example.com", subject: "Summary", text: summary });
    \`\`\`
    Wrapper equivalent:
    \`\`\`js
    const mails = await home.step("Read unread mail", () => home.google.gmail.search("is:unread", 10));
    await home.step("Summarise and send", async () => {
      const summary = await home.ai.chat("Summarise: " + JSON.stringify(mails));
      await home.mail.send({ to: "me@example.com", subject: "Summary", text: summary });
    });
    \`\`\`
- IMPORTANT: use only the methods listed above, with their exact signatures. Never call a method \`home\` does not have (no \`drive.upload\` with an id/range, no \`.values\`).

Answer ONLY with a JSON object in this format (no surrounding text):
${jsonContract}`;
}

const SCRIPT_SYSTEM_SCHEDULE = buildScriptSystem("schedule");

function scriptSystem(triggerKind: TriggerKind): string {
  return triggerKind === "schedule" ? SCRIPT_SYSTEM_SCHEDULE : buildScriptSystem(triggerKind);
}

const SCRIPT_PLANNER_SYSTEM = `You are a technical project manager. The user wants to create a scheduled household job (script).
Analyse the request and answer with ONLY a JSON object in this format:
{
  "summary": "one-sentence summary of the job",
  "steps": ["the steps the job will run, point by point"],
  "data": ["data to read or write (storage, connected services)"],
  "scheduleIntent": "schedule in plain language (e.g. every Monday at 8am, every 30 minutes)",
  "risks": ["points needing attention (e.g. service not connected, 60 s runner limit)"]
}
No text other than the JSON.`;

const SCRIPT_PLANNER_ITERATION_SYSTEM = `You are modifying an existing scheduled household job (script): the user wants to evolve or fix a script already in use.
Analyse the request (and the context provided) and answer with ONLY a JSON object in this format:
{
  "summary": "one-sentence summary of the request",
  "steps": ["modifications to make, point by point"],
  "keep": ["existing elements to preserve (storage keys, behaviour, schedule)"],
  "scheduleIntent": "schedule in plain language (e.g. every Monday at 8am), or \"unchanged\" when it stays the same",
  "risks": ["regression risks or points to watch"]
}
No text other than the JSON.`;

const SCRIPT_PLANNER_SYSTEM_MANUAL = `You are a technical project manager. The user wants to create a household server job triggered on demand (manually).
Analyse the request and answer with ONLY a JSON object in this format:
{
  "summary": "one-sentence summary of the job",
  "steps": ["the steps the job will run, point by point"],
  "data": ["data to read or write (storage, connected services)"],
  "risks": ["points needing attention (e.g. service not connected, 60 s runner limit)"]
}
No text other than the JSON.`;

const SCRIPT_PLANNER_SYSTEM_WEBHOOK = `You are a technical project manager. The user wants to create a household server job triggered by an inbound webhook (public POST to a URL).
Analyse the request and answer with ONLY a JSON object in this format:
{
  "summary": "one-sentence summary of the job",
  "steps": ["the steps the job will run on every webhook call, point by point"],
  "data": ["data to read or write (including the webhook body, exposed through home.webhook.payload)"],
  "risks": ["points needing attention (e.g. service not connected, 60 s runner limit)"]
}
No text other than the JSON.`;

const SCRIPT_PLANNER_ITERATION_SYSTEM_MANUAL = `You are modifying an existing household server job triggered on demand (manual).
Analyse the request (and the context provided) and answer with ONLY a JSON object in this format:
{
  "summary": "one-sentence summary of the request",
  "steps": ["modifications to make, point by point"],
  "keep": ["existing elements to preserve (storage keys, behaviour)"],
  "risks": ["regression risks or points to watch"]
}
No text other than the JSON.`;

const SCRIPT_PLANNER_ITERATION_SYSTEM_WEBHOOK = `You are modifying an existing household server job triggered by an inbound webhook.
Analyse the request (and the context provided) and answer with ONLY a JSON object in this format:
{
  "summary": "one-sentence summary of the request",
  "steps": ["modifications to make, point by point"],
  "keep": ["existing elements to preserve (storage keys, behaviour, use of home.webhook.payload)"],
  "risks": ["regression risks or points to watch"]
}
No text other than the JSON.`;

/**
 * Without the SDK's real method list, the planner invents plausible methods that
 * the coder then faithfully implements (e.g. `webhook.call` to write to Drive).
 */
function plannerCapabilities(): string {
  return `\n\nREAL CAPABILITIES OF THE \`home\` SDK — a job can ONLY do this:
    - \`home.storage.*\` (the script's KV), \`home.app(appId).storage.*\` (an app's KV), \`home.storage.global.*\`
    - \`home.http.fetch(url, init?)\`, \`home.browser.*\`, \`home.ai.chat/messages\`
${getSdkPromptLines("home").join("\n    ")}
A step must never mention a method absent from this list, nor repurpose a method (\`webhook.call\` calls an outbound webhook; it does not write to Drive or anywhere else). If the request exceeds these capabilities, say so in \`risks\` rather than inventing a step.\n\nNo text other than the JSON.`;
}

function buildPlannerSystem(isIterating: boolean, triggerKind: TriggerKind): string {
  const base = () => {
    if (isIterating) {
      if (triggerKind === "manual") return SCRIPT_PLANNER_ITERATION_SYSTEM_MANUAL;
      if (triggerKind === "webhook") return SCRIPT_PLANNER_ITERATION_SYSTEM_WEBHOOK;
      return SCRIPT_PLANNER_ITERATION_SYSTEM;
    }
    if (triggerKind === "manual") return SCRIPT_PLANNER_SYSTEM_MANUAL;
    if (triggerKind === "webhook") return SCRIPT_PLANNER_SYSTEM_WEBHOOK;
    return SCRIPT_PLANNER_SYSTEM;
  };
  return base() + plannerCapabilities();
}

type GeneratedScript = {
  name: string;
  schedule: string;
  code: string;
  durationMs: number;
  coderModel: string;
};

/** Extracts the {name, schedule, code} JSON from the coder's response, with safe defaults. */
function parseGeneratedScript(
  text: string,
  fallback?: { name?: string; schedule?: string; code?: string },
  defaultSchedule = "",
): { name: string; schedule: string; code: string } {
  let parsed: { name?: string; schedule?: string; code?: string } = {};
  const json = text.match(/\{[\s\S]*\}/);
  if (json) {
    try {
      parsed = JSON.parse(json[0]);
    } catch {
      parsed = {};
    }
  }
  return {
    name: parsed.name ?? fallback?.name ?? "Script",
    schedule: parsed.schedule ?? fallback?.schedule ?? defaultSchedule,
    code: parsed.code ?? fallback?.code ?? `async function main(home) {\n  console.log("ok");\n}`,
  };
}

/**
 * Generates a complete script (schedule + code) from a prompt in a single pass.
 * Mostly used by the assistant and MCP; the UI goes through planScript + codeScript.
 */
export async function generateScript(
  prompt: string,
  opts: GenerateOptions = {},
): Promise<GeneratedScript> {
  const coderModel = opts.coderModel ?? defaultModels.coder;
  const triggerKind = opts.triggerKind ?? "schedule";

  const t = Date.now();
  const chat = await chatWithTruncationRetry(
    [
      { role: "system", content: scriptSystem(triggerKind) + languageInstruction(opts.locale) },
      { role: "user", content: prompt },
    ],
    {
      provider: opts.provider,
      model: coderModel,
      maxTokens: 4096,
      userId: opts.userId,
      feature: opts.feature ?? "script_generate",
      appId: null,
      scriptId: opts.scriptId ?? null,
    },
    (_text, finishReason) => finishReason === "length",
  );
  const { name, schedule, code } = parseGeneratedScript(chat.text, undefined, scheduleFallback(triggerKind));

  return { name, schedule, code, durationMs: Date.now() - t, coderModel };
}

export interface StreamCallbacks {
  onToken?: (token: string) => void;
  signal?: AbortSignal;
}

/** Streamed version of generateScript: pushes tokens through onToken. */
export async function generateScriptStream(
  prompt: string,
  opts: GenerateOptions & StreamCallbacks = {},
): Promise<GeneratedScript> {
  const coderModel = opts.coderModel ?? defaultModels.coder;
  const triggerKind = opts.triggerKind ?? "schedule";
  const t = Date.now();
  const { text } = await chatCompletionStream(
    [
      { role: "system", content: scriptSystem(triggerKind) + languageInstruction(opts.locale) },
      { role: "user", content: prompt },
    ],
    {
      provider: opts.provider,
      model: coderModel,
      maxTokens: 4096,
      signal: opts.signal,
      onToken: opts.onToken,
      userId: opts.userId,
      feature: opts.feature ?? "script_generate",
      appId: null,
      scriptId: opts.scriptId ?? null,
    },
  );
  const { name, schedule, code } = parseGeneratedScript(text, undefined, scheduleFallback(triggerKind));
  return { name, schedule, code, durationMs: Date.now() - t, coderModel };
}

/**
 * Modifies an existing script from a new prompt: injects the current code as
 * context and returns the updated fields.
 */
export async function refineScript(
  current: { name: string; schedule: string; code: string },
  prompt: string,
  opts: GenerateOptions = {},
): Promise<GeneratedScript> {
  const coderModel = opts.coderModel ?? defaultModels.coder;
  const triggerKind = opts.triggerKind ?? "schedule";
  const jsonFields = triggerKind === "schedule" ? " (name, schedule, code)" : " (name, code)";

  const t = Date.now();
  const chat = await chatWithTruncationRetry(
    [
      { role: "system", content: scriptSystem(triggerKind) + languageInstruction(opts.locale) },
      {
        role: "user",
        content: `Here is the current script:
Name: ${current.name}
Schedule: ${current.schedule || "—"}
\`\`\`js
${current.code}
\`\`\`

Modification request:
${prompt}

Answer with the complete JSON${jsonFields} reflecting the modified script.`,
      },
    ],
    {
      provider: opts.provider,
      model: coderModel,
      maxTokens: 4096,
      userId: opts.userId,
      feature: opts.feature ?? "script_code",
      appId: null,
      scriptId: opts.scriptId ?? null,
    },
    (_text, finishReason) => finishReason === "length",
  );
  const text = chat.text;

  const result = parseGeneratedScript(text, current, scheduleFallback(triggerKind));

  return { ...result, durationMs: Date.now() - t, coderModel };
}

/** Streamed version of refineScript. */
export async function refineScriptStream(
  current: { name: string; schedule: string; code: string },
  prompt: string,
  opts: GenerateOptions & StreamCallbacks = {},
): Promise<GeneratedScript> {
  const coderModel = opts.coderModel ?? defaultModels.coder;
  const triggerKind = opts.triggerKind ?? "schedule";
  const jsonFields = triggerKind === "schedule" ? " (name, schedule, code)" : " (name, code)";
  const t = Date.now();
  const { text } = await chatCompletionStream(
    [
      { role: "system", content: scriptSystem(triggerKind) + languageInstruction(opts.locale) },
      {
        role: "user",
        content: `Here is the current script:
Name: ${current.name}
Schedule: ${current.schedule || "—"}
\`\`\`js
${current.code}
\`\`\`

Modification request:
${prompt}

Answer with the complete JSON${jsonFields} reflecting the modified script.`,
      },
    ],
    {
      provider: opts.provider,
      model: coderModel,
      maxTokens: 4096,
      signal: opts.signal,
      onToken: opts.onToken,
      userId: opts.userId,
      feature: opts.feature ?? "script_code",
      appId: null,
      scriptId: opts.scriptId ?? null,
    },
  );
  const result = parseGeneratedScript(text, current, scheduleFallback(triggerKind));
  return { ...result, durationMs: Date.now() - t, coderModel };
}

// ---------------------------------------------------------------------------
// Two-phase generation (plan → code), same model as the apps.
// The "plan" phase stops on an editable plan the user validates; the "code"
// phase produces the {name, schedule, code} JSON from that plan.
// ---------------------------------------------------------------------------

export interface ScriptPlanResult {
  plan: string;
  model: string;
}

/** Iteration context for the planner: current script (truncated) + history. */
function plannerContext(
  current: { name: string; schedule: string; code: string } | null,
  historyBlock: string,
): string {
  const lines: string[] = [];
  if (current) {
    lines.push(
      [
        "Context — the script already exists:",
        `Name: ${current.name}`,
        `Schedule: ${current.schedule}`,
        `Current code (truncated):\n\`\`\`js\n${truncateCode(current.code)}\n\`\`\``,
      ].join("\n"),
    );
  }
  if (historyBlock) lines.push(historyBlock);
  return lines.join("\n\n");
}

/** Phase 1: planning a script (creation or iteration). */
export async function planScript(
  prompt: string,
  opts: GenerateOptions & {
    isIterating?: boolean;
    current?: { name: string; schedule: string; code: string } | null;
    historyBlock?: string;
  } = {},
): Promise<ScriptPlanResult> {
  const plannerModel = opts.plannerModel ?? defaultModels.planner;
  const triggerKind = opts.triggerKind ?? "schedule";
  const isIterating = opts.isIterating ?? Boolean(opts.current);
  const context = plannerContext(opts.current ?? null, opts.historyBlock ?? "");

  const planText = await chatCompletion(
    [
      {
        role: "system",
        content: buildPlannerSystem(isIterating, triggerKind) + languageInstruction(opts.locale),
      },
      {
        role: "user",
        content: context ? `${prompt}\n\n${context}` : prompt,
      },
    ],
    {
      provider: opts.provider,
      model: plannerModel,
      maxTokens: 1024,
      userId: opts.userId,
      feature: opts.feature ?? "script_plan",
      appId: null,
      scriptId: opts.scriptId ?? null,
    },
  );
  return { plan: planText, model: plannerModel };
}

/** Streamed phase 1: pushes tokens through onToken. */
export async function planScriptStream(
  prompt: string,
  opts: GenerateOptions &
    StreamCallbacks & {
      isIterating?: boolean;
      current?: { name: string; schedule: string; code: string } | null;
      historyBlock?: string;
    } = {},
): Promise<ScriptPlanResult> {
  const plannerModel = opts.plannerModel ?? defaultModels.planner;
  const triggerKind = opts.triggerKind ?? "schedule";
  const isIterating = opts.isIterating ?? Boolean(opts.current);
  const context = plannerContext(opts.current ?? null, opts.historyBlock ?? "");
  const planText = await chatCompletionStream(
    [
      {
        role: "system",
        content: buildPlannerSystem(isIterating, triggerKind) + languageInstruction(opts.locale),
      },
      {
        role: "user",
        content: context ? `${prompt}\n\n${context}` : prompt,
      },
    ],
    {
      provider: opts.provider,
      model: plannerModel,
      maxTokens: 1024,
      signal: opts.signal,
      onToken: opts.onToken,
      userId: opts.userId,
      feature: opts.feature ?? "script_plan",
      appId: null,
      scriptId: opts.scriptId ?? null,
    },
  ).then((r) => r.text);
  return { plan: planText, model: plannerModel };
}

/** Phase 2: code implementation from the validated plan. */
export async function codeScript(
  prompt: string,
  plan: string,
  opts: GenerateOptions & {
    current?: { name: string; schedule: string; code: string } | null;
  } = {},
): Promise<GeneratedScript> {
  const coderModel = opts.coderModel ?? defaultModels.coder;
  const triggerKind = opts.triggerKind ?? "schedule";
  const t = Date.now();
  const chat = await chatWithTruncationRetry(
    [
      { role: "system", content: scriptSystem(triggerKind) + languageInstruction(opts.locale) },
      {
        role: "user",
        content: `Here is the current script:
Name: ${opts.current?.name ?? "—"}
Schedule: ${opts.current?.schedule || "—"}
${opts.current ? `\`\`\`js\n${opts.current.code}\n\`\`\`` : "—"}

Request: ${prompt}

Proposed plan:
${plan}

The plan is indicative: if a step mentions a method absent from the SDK above, ignore it (do not replace it with an approximate call) and flag it in the code with a comment.
Answer with the complete JSON reflecting the script (modified when iterating).`,
      },
    ],
    {
      provider: opts.provider,
      model: coderModel,
      maxTokens: 4096,
      userId: opts.userId,
      feature: opts.feature ?? "script_code",
      appId: null,
      scriptId: opts.scriptId ?? null,
    },
    (_text, finishReason) => finishReason === "length",
  );
  const result = parseGeneratedScript(chat.text, opts.current ?? undefined, scheduleFallback(triggerKind));
  return { ...result, durationMs: Date.now() - t, coderModel };
}

/** Streamed phase 2: pushes tokens through onToken. */
export async function codeScriptStream(
  prompt: string,
  plan: string,
  opts: GenerateOptions &
    StreamCallbacks & {
      current?: { name: string; schedule: string; code: string } | null;
    } = {},
): Promise<GeneratedScript> {
  const coderModel = opts.coderModel ?? defaultModels.coder;
  const triggerKind = opts.triggerKind ?? "schedule";
  const t = Date.now();
  const { text } = await chatCompletionStream(
    [
      { role: "system", content: scriptSystem(triggerKind) + languageInstruction(opts.locale) },
      {
        role: "user",
        content: `Here is the current script:
Name: ${opts.current?.name ?? "—"}
Schedule: ${opts.current?.schedule || "—"}
${opts.current ? `\`\`\`js\n${opts.current.code}\n\`\`\`` : "—"}

Request: ${prompt}

Proposed plan:
${plan}

The plan is indicative: if a step mentions a method absent from the SDK above, ignore it (do not replace it with an approximate call) and flag it in the code with a comment.
Answer with the complete JSON reflecting the script (modified when iterating).`,
      },
    ],
    {
      provider: opts.provider,
      model: coderModel,
      maxTokens: 4096,
      signal: opts.signal,
      onToken: opts.onToken,
      userId: opts.userId,
      feature: opts.feature ?? "script_code",
      appId: null,
      scriptId: opts.scriptId ?? null,
    },
  );
  const result = parseGeneratedScript(text, opts.current ?? undefined, scheduleFallback(triggerKind));
  return { ...result, durationMs: Date.now() - t, coderModel };
}
